services:
  # Serviço para o Spark
  spark:
    image: bitnami/spark:3.5.0
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"  # Porta do Spark UI
    networks:
      - football_network
    volumes:
      - ./spark:/opt/spark

  # Serviço para o Streamlit
  streamlit:
    build:
      context: .
    container_name: streamlit
    ports:
      - "8501:8501"  # Porta do Streamlit
    networks:
      - football_network
    volumes:
      - .:/src/app
    command: ["poetry", "run", "streamlit", "run", "frontend/app.py"]
    environment:
      - STREAMLIT_SERVER_ENABLE_WATCHDOG=true
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll

networks:
  football_network:
    driver: bridge
